//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopByEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public string cname { get; set; }
        public string ccontact { get; set; }
        public string caddress { get; set; }
        public string cemail { get; set; }
        public string odate { get; set; }
        public int pquantity { get; set; }
        public string pname { get; set; }
        public string pprice { get; set; }
    }
}
