//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopByEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
        public string ccontact { get; set; }
        public string caddress { get; set; }
        public string cemail { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
